title: Maiane Junqueira
logo: assets/img/foto1.jpg
description: PhD Student
show_downloads: false
#linkedin: https://www.linkedin.com/in/maiane-junqueira-teixeira-neto-2413a387
theme: jekyll-theme-minimal
